### ISSUE TITLE
依旧是 failed to load module from xxx.fake.ts 的问题

### ISSUE THREAD

**Issue by kayanouriko** [condorheroblog/vite-plugin-fake-server#11]
我的项目文件结构加入该插件后大概是这样的: 

```markdown
├── fake
│   ├── utils
│   │   └── tool.ts
│   ├── data
│   │   └── data.json
│   └── test.fake.ts
└── src
    └── code...
```

在 `tsconfig.json` 的 `include` 加入 `"fake/**/*.ts"` 后一切是按预期执行.

现在出现的问题是我在集成后进行代码重构的时候, `defineFakeRoute` 里面例如 `url`, `response` 之类的想 import src 原有的代码复用的时候, 依旧会出现 `failed to load module from xxx` 的报错. 
我把这部分逻辑代码移动到 `fake` 文件夹下面就没问题了, `xxx.fake.ts` 只 import 插件指定文件夹下面的代码才不会报错.

**Comment by condorheroblog** [comment]
```ts
import { url } from "#src/temp";
export default defineFakeRoute([
	{
		url,
		timeout: 1000,
		method: "get",
		response: () => resultSuccess(adminInfo),
	},
]);


// ./src/temp.ts
export const url = "/api/userinfo"
```

我理解你的意思是像上面使用吗，没有复现，如果没有更多信息，先关闭了

**Comment by kayanouriko** [comment]
进一步测试, 我是使用了 [环境变量和模式](https://cn.vitejs.dev/guide/env-and-mode), 在回调使用了 `import.meta.env.VITE_FAKE` 自定义环境变量, 这时候就会报错.

```typescript
// ./src/ts/api.ts
const api = 'https://api.com/'
const path = 'data.json'

function useApi(path: string) {
    if (import.meta.env.VITE_FAKE === 'true') {
        return `fake/${path}`
    }
    return `${api}${path}`
}
```

**Comment by condorheroblog** [comment]
OK，我知道你的意思了，fake-server 插件并没有默认支持 Vite 的 [环境变量](https://cn.vitejs.dev/guide/env-and-mode) 和 [define](https://cn.vitejs.dev/config/shared-options.html#define)。

我写的时候就注意到了这个问题，但是因为我不用这个功能，就没支持，毕竟要费点时间😂

上面代码是你的真实案例吗，我认为无论本地还是生产环境 URL 应该保持一致，这样应该能避免😁
