### ISSUE TITLE
Headers is not defined 

### ISSUE THREAD

**Issue by brosegu** [condorheroblog/vite-plugin-fake-server#14]
在2.0.0和2.0.1版本中，报错Headers is not defined

**Comment by condorheroblog** [comment]
自定义 headers 没有发现错误：

1. XHR https://condorheroblog.github.io/vite-plugin-fake-server/#type=XHR&path=custom-response-header
2. Fetch https://condorheroblog.github.io/vite-plugin-fake-server/#type=Fetch&path=custom-response-header

请提供在线复现链接或者步骤

**Comment by condorheroblog** [comment]
需要 Node.js 18+ 以上的版本，可以在 https://github.com/pure-admin/vue-pure-admin/issues/849 中查看详细回复信息。
