### ISSUE TITLE
💬Who is using vite-plugin-fake-server?👋 

### ISSUE THREAD

**Issue by condorheroblog** [condorheroblog/vite-plugin-fake-server#17]
[vite-plugin-fake-server](https://github.com/condorheroblog/vite-plugin-fake-server) 只是一个工具，最终需要用到项目里面去，随着 [vite-plugin-fake-server](https://github.com/condorheroblog/vite-plugin-fake-server)  使用量（![Week Downloads](https://img.shields.io/npm/dw/vite-plugin-fake-server)）的上升，我们可以通过它知道更多的优秀项目。

下面是从 [dependents](https://github.com/condorheroblog/vite-plugin-fake-server/network/dependents) 中得到的一个表，按时间排序， stars 超过 100:

---

| Name                                                                             | Framework    | Stars                                                                                                            | Last Commit                                                                                                                           |
|:--------------------------------------------------------------------------------:|:------------:|:----------------------------------------------------------------------------------------------------------------:|:-------------------------------------------------------------------------------------------------------------------------------------:|
| [vue-pure-admin](https://github.com/pure-admin/vue-pure-admin)                   | Vue          | ![vue-pure-admin Stars](https://badgen.net/github/stars/pure-admin/vue-pure-admin)                               | ![vue-pure-admin Last Commit](https://badgen.net/github/last-commit/pure-admin/vue-pure-admin)                                        |
| [vue-xs-admin](https://github.com/jsxiaosi/vue-xs-admin)                         | Vue          | ![vue-xs-admin Stars](https://badgen.net/github/stars/jsxiaosi/vue-xs-admin)                                     | ![vue-xs-admin Last Commit](https://badgen.net/github/last-commit/jsxiaosi/vue-xs-admin)                                              |
| [react-xs-admin](https://github.com/jsxiaosi/react-xs-admin)                     | React        | ![react-xs-admin Stars](https://badgen.net/github/stars/jsxiaosi/react-xs-admin)                                 | ![react-xs-admin Last Commit](https://badgen.net/github/last-commit/jsxiaosi/react-xs-admin)                                          |
| [fantastic-admin](https://github.com/fantastic-admin/basic)                      | Vue          | ![fantastic-admin Stars](https://badgen.net/github/stars/fantastic-admin/basic)                                  | ![fantastic-admin Last Commit](https://badgen.net/github/last-commit/fantastic-admin/basic)                                           |

**Comment by zhennann** [comment]
感谢作者优秀的工作。可否添加一个新成员：

- Name: cabloy-front
- Github: https://github.com/cabloy/cabloy-front
- Framework:  Vue
- Stars: https://img.shields.io/github/stars/cabloy/cabloy-front
- Last Commit: https://img.shields.io/github/last-commit/cabloy/cabloy-front
