### ISSUE TITLE
如果 include 目录为空，导致项目无法正常启动

### ISSUE THREAD

**Issue by hooray** [condorheroblog/vite-plugin-fake-server#18]
<img width="517" alt="image" src="https://github.com/condorheroblog/vite-plugin-fake-server/assets/1574903/87ec0730-cb86-4ad8-a10c-5d11fb933322">

也不报错，就一直卡在这个状态

**Comment by condorheroblog** [comment]
在 [v2.1.0](https://github.com/condorheroblog/vite-plugin-fake-server/releases/tag/v2.1.0) 中修复。

谢谢反馈❤️
