### ISSUE TITLE
`vite v5.0.0-beta.10`版本使用问题

### ISSUE THREAD

**Issue by xiaoxian521** [condorheroblog/vite-plugin-fake-server#2]
嘿，很`nice`的项目，不强绑定`mockjs`对于目前生态发展来说太重要了，`mockjs`已经过时了，使用中遇到如下问题，还希望作者有空看看
 
1. 类型报错，如下图

<img width="931" alt="image" src="https://github.com/condorheroblog/vite-plugin-fake-server/assets/44761321/f2606841-f5ef-40c8-9a9d-587f1e09a9b3">

2. `response`里的`body`返回的是字符串，可以返回标准对象跟`vite-plugin-mock`返回格式保持一致吗

<img width="1279" alt="image" src="https://github.com/condorheroblog/vite-plugin-fake-server/assets/44761321/92b88093-3dc0-489a-a0dc-8f62310f496c">

3. 修改`mock`文件后，编辑器控制台报错信息如下：

<img width="1526" alt="image" src="https://github.com/condorheroblog/vite-plugin-fake-server/assets/44761321/ea0e9361-6249-4f93-b1c2-c9d2e708157d">

**Comment by condorheroblog** [comment]
1. 针对第一个问题，我猜测可能是由于 `tsconfig.json` 的配置问题所引起的。你可以尝试参考这个解决方案：[Cannot find type declaration file in TypeScript](https://github.com/condorheroblog/vite-plugin-fake-server/issues/1)。
2. 解析请求体为 JSON 是一个不错的优化，因为 JSON 更加常见，这样请求体的类型就可以定义为 `body: Record<string, any> | string`，我权衡下吧。
3. 最好避免使用 CommonJS (CJS) 文件。在我的测试中，我经常遇到 bundle-require 加载 CJS 文件时出现的错误。因此，默认情况下，我没有对 CJS 文件提供支持。

谢谢你的反馈🙏

**Comment by condorheroblog** [comment]
[ v0.0.3](https://github.com/condorheroblog/vite-plugin-fake-server/tree/v0.0.3) is released.

**Comment by xiaoxian521** [comment]
嘿，最新版已经满足整体需求，还有些小优化需求，作者如果有空的话，帮看看 ❤️

`mock`文件故意写错代码，编辑器控制台会报红色的错误信息，如下图

<img width="1097" alt="image" src="https://github.com/condorheroblog/vite-plugin-fake-server/assets/44761321/bb1541be-be75-408f-8d07-1514084fd532">

可以选择使用类似下面的报错，让用户不觉得那么显眼

<img width="633" alt="image" src="https://github.com/condorheroblog/vite-plugin-fake-server/assets/44761321/f1772d46-2235-452a-8143-5f3d4a378ae7">

当然更好的是，当用户把错误的代码修改正常，`vite-plugin-fake-server`提供个类似`clearScreen`配置项，配置后可以自动把之前输出的错误信息清除就完美啦
