### ISSUE TITLE
有2个问题咨询一下

### ISSUE THREAD

**Issue by jinmao88** [condorheroblog/vite-plugin-fake-server#21]
1. *.mock.ts 文件中 不能存在export default以外的export，
2. *.mock.ts 文件中 只能import相对路径，不可引入 '@vben/util/mock-util'
能修复一下么

**Comment by condorheroblog** [comment]
1. 放开使用 export 可能导致代码比较混乱，所以如果想导出多个，直接 export default 一个数组就行。
2. Mock 文件中可以使用 mockjs 和 fake.js 第三方包，甚至也支持 TypeScript 配置中的别名，所以你的第二个问题应该是不存在的。

**Comment by jinmao88** [comment]
第二个问题还好有日志提示 改一下就行
第一个问题 我是排查了很久才发现的 最好写个提示

**Comment by jinmao88** [comment]
export的问题会导致开发环境可用 生产环境失效的问题

**Comment by jinmao88** [comment]
mororepo 导入本地其他包 是会提示导入失效的
