### ISSUE TITLE
使用 node 18.0.0 报错

### ISSUE THREAD

**Issue by hooray** [condorheroblog/vite-plugin-fake-server#22]
<img width="814" alt="image" src="https://github.com/condorheroblog/vite-plugin-fake-server/assets/1574903/ab9bee45-b33e-40d7-a5eb-22ee6d331258">

使用最新的 18.19.1 是正常的

---

另外使用 18 以下版本也会有报错，比如使用 16 ，但报错的内容不一样。不过考虑到 vite 目前最低版本要求就是 18+/20+ ，在16下使用的问题可以考虑不管，但最好能在readme里有说明最低使用版本要求。

**Comment by condorheroblog** [comment]
不错的建议，有时间我加一下🤗
