### ISSUE TITLE
vitepress中使用问题

### ISSUE THREAD

**Issue by jinghui70** [condorheroblog/vite-plugin-fake-server#23]
vitepress写作文档，dev模式使用fake-server没有问题，vitepress的index.html,是使用index.md生成的，enableProd目前不起作用

**Comment by condorheroblog** [comment]
你解决这个问题了吗？

fake-server 本身没有针对 vitepress 做兼容处理，我初步调研了一下，vitepress build 的时候可以使用 vitepress  的 transformHead 进行一些特殊处理，需要写点代码实现。

我现在没有时间搞这个，可能未来找个时间弄一下。

**Comment by jinghui70** [comment]
Vitepress 中使用，可能是个小众需求。我是简单粗暴解决这个问题的。
在 theme 目录下添加了 fakeserver 目录，把插件添加到 index.html的js 文件（getResponse.js, xhook.js, index.js）放到这个目录下，然后在index.js中添加以下内容：

if (import.meta.env.PROD) {
  import('./fakeserver')
}

**Comment by condorheroblog** [comment]
Good job👍

**Comment by taoyimin** [comment]
> Vitepress 中使用，可能是个小众需求。我是简单粗暴解决这个问题的。 在 theme 目录下添加了 fakeserver 目录，把插件添加到 index.html的js 文件（getResponse.js, xhook.js, index.js）放到这个目录下，然后在index.js中添加以下内容：
> 
> if (import.meta.env.PROD) { import('./fakeserver') }

你好，我在vitepress也遇到生产环境没有生效的问题，请问可以详细讲下怎么解决吗？“把插件添加到 index.html的js 文件（getResponse.js, xhook.js, index.js）放到这个目录下”这句话啥意思，没太看懂。
