### ISSUE TITLE
希望能和 vite-plugin-mock一样，支持正则url，这样就能无缝切换不用怎么改代码

### ISSUE THREAD

**Issue by softshield** [condorheroblog/vite-plugin-fake-server#24]
希望能和 vite-plugin-mock一样，支持正则url，这样就能无缝切换不用怎么改代码

**Comment by condorheroblog** [comment]
插件目前支持的功能应该能满足你的需求吧，如果你不使用正则会有比较大的困难吗🤔

**Comment by condorheroblog** [comment]
我使用的是 path-to-regexp 处理 path， 照理讲是支持正则的。
