### ISSUE TITLE
引入 mockjs 并调用Random的ctitle等函数会报错

### ISSUE THREAD

**Issue by softshield** [condorheroblog/vite-plugin-fake-server#25]
引入mockjs并调用Random的ctitle等函数会报错。
环境：node18、node20
报错：
‘[vite-plugin-fake-server] failed to load module from mock\refreshToken.ts’

**Comment by condorheroblog** [comment]
应该是你写法的问题，你排查下(¬‿¬)

**Comment by softshield** [comment]
import Mock from "mockjs";

**Comment by softshield** [comment]
尝试了下，正确的写法：
import Mock from "mockjs";
const Random = Mock.Random;

报错的写法：
import  {Random} from "mockjs";

---------------------------------
mockjs 1.1
node 20
基于pure-admin-thin 5.1

这是啥原因？

**Comment by condorheroblog** [comment]
包没有单独导出 Random 呗

**Comment by softshield** [comment]
import {Random} from "mockjs";
这个写法，在业务层是没问题的。

就是不能写在 vite.config.ts 及其插件里面。。。

**Comment by condorheroblog** [comment]
没问题是打包工具帮你处理了，按官方的示例来，一定没有问题(｡•̀ᴗ-)✧

你正确的写法符合它们的代码，也符合他们文档示例，所以就按这个来吧
