### ISSUE TITLE
ts类型报错

### ISSUE THREAD

**Issue by thikiiii** [condorheroblog/vite-plugin-fake-server#26]
报错信息：Cannot find module vite-plugin-fake-server/client or its corresponding type declarations.
```js
 // Cannot find module vite-plugin-fake-server/client or its corresponding type declarations.
 import { defineFakeRoute } from 'vite-plugin-fake-server/client'
```
tsconfig配置
```json
{
  "compilerOptions": {
    "target": "ESNext",
    "module": "ESNext",
    "moduleResolution": "bundler",
    "strict": true,
    "jsxImportSource": "vue",
    "forceConsistentCasingInFileNames": true,
    "allowSyntheticDefaultImports": true,
    "strictFunctionTypes": false,
    "jsx": "preserve",
    "baseUrl": ".",
    "allowJs": true,
    "sourceMap": true,
    "esModuleInterop": true,
    "resolveJsonModule": true,
    "noUnusedLocals": false,
    "isolatedModules": true,
    "noUnusedParameters": false,
    "experimentalDecorators": true,
    "skipLibCheck": true,
    "noEmit": true,
    "lib": ["dom", "esnext"],
    "types": ["node"],
    "typeRoots": ["./node_modules/@types/", "./types", "./node_modules"],
    "noImplicitAny": false,
    "paths": {
      "@/*": ["src/*"],
      "#/*": ["types/*"]
    }
  },
  "include": [
    "src/**/*.ts",
    "src/**/*.d.ts",
    "src/**/*.tsx",
    "src/**/*.vue",
    "types/**/*.d.ts",
    "types/**/*.ts",
    "build/**/*.ts",
    "build/**/*.d.ts",
    "mock/**/*.ts",
    "vite.config.ts",
    "uno.config.ts"
  ],
  "exclude": ["node_modules", "dist", "**/*.js"],
  "type": ["node"]
}
```
系统版本
```
vite-plugin-fake-server:2.1.1
node:18.19.0
vite:5.1.6
typescript:5.3.3
```

**Comment by thikiiii** [comment]
> 报错信息：找不到模块 vite-plugin-fake-server/client 或其相应的类型声明。
> 
> ```js
>  // Cannot find module vite-plugin-fake-server/client or its corresponding type declarations.
>  import { defineFakeRoute } from 'vite-plugin-fake-server/client'
> ```
> 
> tsconfig配置
> 
> ```json
> {
>   "compilerOptions": {
>     "target": "ESNext",
>     "module": "ESNext",
>     "moduleResolution": "bundler",
>     "strict": true,
>     "jsxImportSource": "vue",
>     "forceConsistentCasingInFileNames": true,
>     "allowSyntheticDefaultImports": true,
>     "strictFunctionTypes": false,
>     "jsx": "preserve",
>     "baseUrl": ".",
>     "allowJs": true,
>     "sourceMap": true,
>     "esModuleInterop": true,
>     "resolveJsonModule": true,
>     "noUnusedLocals": false,
>     "isolatedModules": true,
>     "noUnusedParameters": false,
>     "experimentalDecorators": true,
>     "skipLibCheck": true,
>     "noEmit": true,
>     "lib": ["dom", "esnext"],
>     "types": ["node"],
>     "typeRoots": ["./node_modules/@types/", "./types", "./node_modules"],
>     "noImplicitAny": false,
>     "paths": {
>       "@/*": ["src/*"],
>       "#/*": ["types/*"]
>     }
>   },
>   "include": [
>     "src/**/*.ts",
>     "src/**/*.d.ts",
>     "src/**/*.tsx",
>     "src/**/*.vue",
>     "types/**/*.d.ts",
>     "types/**/*.ts",
>     "build/**/*.ts",
>     "build/**/*.d.ts",
>     "mock/**/*.ts",
>     "vite.config.ts",
>     "uno.config.ts"
>   ],
>   "exclude": ["node_modules", "dist", "**/*.js"],
>   "type": ["node"]
> }
> ```
> 
> 系统版本
> 
> ```
> vite-plugin-fake-server:2.1.1
> node:18.19.0
> vite:5.1.6
> typescript:5.3.3
> ```

```js
// 这个没有报错
import { vitePluginFakeServer } from 'vite-plugin-fake-server'
```

**Comment by thikiiii** [comment]
```ts
// 这个没有报错
import { vitePluginFakeServer } from 'vite-plugin-fake-server'
```

**Comment by condorheroblog** [comment]
应该是 moduleResolution 值的问题，参见  https://github.com/condorheroblog/vite-plugin-fake-server/issues/1，修改下重启 VSCode 试试。

**Comment by thikiiii** [comment]
不好意思，我的问题

**Comment by thikiiii** [comment]
我tsconfig里的include没有包含fake
