### ISSUE TITLE
feature request: Beautify log output and add screen clearing function

### ISSUE THREAD

**Issue by condorheroblog** [condorheroblog/vite-plugin-fake-server#3]
嘿，最新版已经满足整体需求，还有些小优化需求，作者如果有空的话，帮看看 ❤️

`mock`文件故意写错代码，编辑器控制台会报红色的错误信息，如下图

<img width="1097" alt="image" src="https://github.com/condorheroblog/vite-plugin-fake-server/assets/44761321/bb1541be-be75-408f-8d07-1514084fd532">

可以选择使用类似下面的报错，让用户不觉得那么显眼

<img width="633" alt="image" src="https://github.com/condorheroblog/vite-plugin-fake-server/assets/44761321/f1772d46-2235-452a-8143-5f3d4a378ae7">

当然更好的是，当用户把错误的代码修改正常，`vite-plugin-fake-server`提供个类似`clearScreen`配置项，配置后可以自动把之前输出的错误信息清除就完美啦

_Originally posted by @xiaoxian521 in https://github.com/condorheroblog/vite-plugin-fake-server/issues/2#issuecomment-1772385354_

---

To sum up the following two points:

1. A log consistent with Vite style
2. Add clear screen

**Comment by xiaoxian521** [comment]
nice 坐等作者更新版本和文档 😻

**Comment by condorheroblog** [comment]
![shapes at 23-10-24 15 23 18](https://github.com/condorheroblog/vite-plugin-fake-server/assets/47056890/a6b11fcb-ee30-40a5-9beb-b1d9a0a51b39)

优化成上面这样了，基本上和 Vite 的表现一致。

[v1.0.0](https://github.com/condorheroblog/vite-plugin-fake-server/releases/tag/v1.0.0) is released.

**Comment by xiaoxian521** [comment]
升级后 请求都404 可以使用 https://github.com/pure-admin/vue-pure-admin/tree/refactor/fake-server 代码复习哦
<img width="1185" alt="image" src="https://github.com/condorheroblog/vite-plugin-fake-server/assets/44761321/c745778f-afc2-4773-bc40-3174ee419cd8">

**Comment by condorheroblog** [comment]
我操作如下，没有复现，正常使用哇：

1. 拉取 `refactor/fake-server` 的代码
2. 升级 `vite-plugin-fake-server` 到 v1.0.0
3. 安装依赖
4. 启动项目
5. 系统管理—用户管理页面复现
6. 未复现

![2023-10-25 12-48-52 2023-10-25 12_53_04](https://github.com/condorheroblog/vite-plugin-fake-server/assets/47056890/7085b36e-f9fa-4ac7-a7e7-54c17ec065c6)

**Comment by xiaoxian521** [comment]
😂 嗯嗯 是因为我修改了mock文件 还在错误的基础之上加载文件导致的

**Comment by xiaoxian521** [comment]
最后一个问题 重启动会显示下图报错是什么原因呢🤔
<img width="985" alt="image" src="https://github.com/condorheroblog/vite-plugin-fake-server/assets/44761321/0e2ef6bb-20c2-43ed-806d-3a5e8be715da">
