### ISSUE TITLE
In some environments, Headers is not defined.

### ISSUE THREAD

**Issue by imycod** [condorheroblog/vite-plugin-fake-server#31]
![image](https://github.com/user-attachments/assets/89a2609c-2b60-4bde-a5b2-7d6883de63c8)
 responseHeaders: new Headers({ ...globalResponseHeaders, ...responseHeaders }), ReferenceError: Headers is not defined
------------
node 16.20.2
vite 5.0.6
npm 8.19.4
vite-plugin-fake-server 2.1.1

but i use this code with chatgpt ```js // Ensure Headers is available
const Headers = globalThis.Headers || (() => {
  // A simple polyfill for Headers if not available
  class SimpleHeaders {
    constructor(headers) {
      this.headers = {};
      for (const key in headers) {
        if (headers.hasOwnProperty(key)) {
          this.headers[key.toLowerCase()] = headers[key];
        }
      }
    }
    append(name, value) {
      this.headers[name.toLowerCase()] = value;
    }
    get(name) {
      return this.headers[name.toLowerCase()] || null;
    }
    has(name) {
      return this.headers.hasOwnProperty(name.toLowerCase());
    }
    keys() {
      return Object.keys(this.headers);
    }
  }
  return SimpleHeaders;
})(); ``` solved my problem.I don't know if other questions will be introduced. If anyone encounters them, they can refer to them.

**Comment by condorheroblog** [comment]
Same issue https://github.com/condorheroblog/vite-plugin-fake-server/issues/27

The environment requires a version of Node.js greater than 18.
