### ISSUE TITLE
可以加一个给url加前缀的属性吗？

### ISSUE THREAD

**Issue by thikiiii** [condorheroblog/vite-plugin-fake-server#33]
类似`axios`的`baseURL`

**Comment by condorheroblog** [comment]
https://github.com/condorheroblog/vite-plugin-fake-server/blob/0749fce8686711d3527fca246aae238a37f5828c/packages/playground/react-sample/vite.config.ts#L11

https://github.com/condorheroblog/vite-plugin-fake-server?tab=readme-ov-file#basename
