### ISSUE TITLE
fix(修复某些框架利用new XMLHttpRequest responseType 检测是否支持xhr2)

### ISSUE THREAD

**Issue by boommanpro** [condorheroblog/vite-plugin-fake-server#35]
link PR: https://github.com/condorheroblog/vite-plugin-fake-server/pull/34
求合并后发最个最新版本，求求求~

**Comment by condorheroblog** [comment]
Closed [v2.1.2](https://github.com/condorheroblog/vite-plugin-fake-server/releases/tag/v2.1.2)
