### ISSUE TITLE
在vitepress中使用，开发环境正常，生产环境404

### ISSUE THREAD

**Issue by taoyimin** [condorheroblog/vite-plugin-fake-server#36]
在vitepress中使用，生产环境报错，有解决方案吗？
![image](https://github.com/user-attachments/assets/3685dc08-076f-43cb-b8d5-05bb8a51c793)
![image](https://github.com/user-attachments/assets/031b2802-bfdc-4b90-a119-24ed833695a7)

**Comment by taoyimin** [comment]
跟上面那个错误没关系，那个应该是vitepress的报错，但是不知道为什么一到生产环境mock数据就404了。

**Comment by condorheroblog** [comment]
VitePress 是 SSG，用来生成多页面的，当前仓库的代码只对 SPG 项目有效。
