### ISSUE TITLE
`vite6.0.0-beta.8`打包预览报错

### ISSUE THREAD

**Issue by xiaoxian521** [condorheroblog/vite-plugin-fake-server#37]
作者，你好，目前在升级`vite6`时遇到`vite-plugin-fake-server`打包后报错，如下图

<img width="1653" alt="image" src="https://github.com/user-attachments/assets/26a3be0c-2fa0-4801-a845-c20f6d011973">

`vite6.0.0-beta.8`已接近正式版 https://github.com/vitejs/vite/milestone/17

可能是`vite6`正式引入了 [环境概念](https://cn.vitejs.dev/guide/api-environment.html#formalizing-environments) 带来了一些`Break Change`

**Comment by condorheroblog** [comment]
错误显示无法获取 path-to-regexp 的 match 方法，path-to-regexp 是通过 Vite 打包到浏览器的 

https://github.com/condorheroblog/vite-plugin-fake-server/blob/c981a3a0d05c5d31fd38d91cb8db3c8647b4bd89/packages/vite-plugin-fake-server/src/utils/buildPackage.ts#L6-L47

但是在 Vite6 中的输出不一致了 😅

![image](https://github.com/user-attachments/assets/699a1f7e-a8e5-4ff9-8fce-a6c0a694f740)

**Comment by condorheroblog** [comment]
不知道这算不算是他们的一个 bug😂

**Comment by condorheroblog** [comment]
https://github.com/vitejs/vite/issues/18574

管他的，先提一个 bug 😂

**Comment by condorheroblog** [comment]
Rollup 把 strictRequires 默认值从 auto 改为 true 了，我在打包的时候强制指定打包参数 strictRequires 还为 "auto"。

```
build: {
	commonjsOptions: {
		strictRequires: "auto",
	},
},
```

同时在代码中增加判断逻辑——没有别名导出就使用默认导出。

**Comment by condorheroblog** [comment]
[v2.1.3](https://github.com/condorheroblog/vite-plugin-fake-server/releases/tag/v2.1.3) 已经发布
