### ISSUE TITLE
v2.1.3 无法监听文件变化

### ISSUE THREAD

**Issue by hooray** [condorheroblog/vite-plugin-fake-server#38]
v2.1.3 mock文件修改后不会更新，需要重启vite才行，v2.1.2正常

**Comment by condorheroblog** [comment]
chokidar 在 v4 删除了对 glob 语法的支持，非常抱歉升级依赖我没看清楚，我改下代码😅

**Comment by condorheroblog** [comment]
请使用 [v2.1.4](https://github.com/condorheroblog/vite-plugin-fake-server/releases/tag/v2.1.4)
