### ISSUE TITLE
使用同步请求后的问题

### ISSUE THREAD

**Issue by xiaoxian521** [condorheroblog/vite-plugin-fake-server#39]
作者，你好。冬至快乐 🥟

问题：我在使用 [vditor](https://github.com/Vanessa219/vditor) 中发现它内部使用了同步请求，但浏览器不支持在同步请求上设置` responseType`，因为这会阻塞浏览器的主线程。`vite-plugin-fake-server`中的 [facade.responseType = "";](https://github.com/condorheroblog/vite-plugin-fake-server/blob/main/packages/vite-plugin-fake-server/src/xhook/index.mjs#L614) 不论什么请求都会走到这里，这也导致了下图报错。我注释了`facade.responseType = "";`就好了，但肯定有它的用途，还请作者能帮忙看一下 ❤️ 

![image](https://github.com/user-attachments/assets/e74f3f5a-5c4e-4cbc-8f6e-a2b7769ee238)

![image](https://github.com/user-attachments/assets/19a9fea6-9d6a-4b91-9ac5-1b24f91afc58)

复现地址：https://github.com/pure-admin/vue-pure-admin/tree/feat/Markdown

修改`sourcemap: true` 然后执行`pnpm preview:build` 即可预览复现

<img width="1094" alt="image" src="https://github.com/user-attachments/assets/d145acf0-c1f6-454b-9c8c-4818a566a2d2" />

**Comment by condorheroblog** [comment]
responseType 为空字符串是 XHR 请求中 responseType 的默认值。

之前有人用到了这个值，就添加为空字符串了。https://github.com/condorheroblog/vite-plugin-fake-server/pull/34

现在的代码确实是会阻塞同步请求，如果我改写 xhook 当是同步请求不设置 responseType 就会导致同步请求用户设置了 responseType 但浏览器没有报错。

目前来看就是让 responseType 维持默认值 —— undefined，这样只需要回退下代码，你有好的想法吗😂

**Comment by xiaoxian521** [comment]
那把`responseType`暴露出来个`api`配置吧 如果配置了`responseType: true`就可以执行设置它的值 没有配置或者为`false`就不设置😂

**Comment by xiaoxian521** [comment]
怎么样 有别的解决办法不😄

**Comment by xiaoxian521** [comment]
<img width="886" alt="image" src="https://github.com/user-attachments/assets/294ecbae-1218-4d9b-b043-003af1e9b5b9" />

我发现 `request.async` 在此处总是为 `undefined` 要不就可以通过这个判断处理了

**Comment by condorheroblog** [comment]
初始化的时候 facade.responseType 是空字符串和 request.async 没啥关系，无论 async 的值是真还是假，返回的 responseType 都应该是空字符串。

---

应该可以通过 Object.defineProperty() 来解决这个 bug，我先看看不行的话，就保留 responseType 为 undefined，返回都是假值，可以判断。

**Comment by xiaoxian521** [comment]
好的 responseType 为 undefined 确实没毛病

**Comment by condorheroblog** [comment]
解决了

---

但是现在有一个问题是没办法拦截同步请求，你有需要到吗

**Comment by xiaoxian521** [comment]
同步请求其实不常用
大部分都是异步 不堵塞
主要是别的库用到了 没办法了 
我去测试一下你的最新提交 谢谢

**Comment by condorheroblog** [comment]
OK 不使用的话，先不加了😄

**Comment by xiaoxian521** [comment]
可以了 不报错了 👍

**Comment by condorheroblog** [comment]
行，我发布了 [v2.1.5](https://github.com/condorheroblog/vite-plugin-fake-server/releases/tag/v2.1.5)

**Comment by condorheroblog** [comment]
我初步实现了 [XHR Sync request](https://condorheroblog.github.io/vite-plugin-fake-server/#type=XHR&path=sync-request)

在你的项目，有什么好的使用案例吗

**Comment by xiaoxian521** [comment]
没 只是[vditor](https://github.com/Vanessa219/vditor) 源码用了
