### ISSUE TITLE
Doesn't work on Windows

### ISSUE THREAD

**Issue by condorheroblog** [condorheroblog/vite-plugin-fake-server#5]
还有个问题是在`windows`上请求会404 今天刚用windows测试 我的谷歌浏览器是刚下载了 所以很干净 应该不是插件影响
![image](https://github.com/condorheroblog/vite-plugin-fake-server/assets/44761321/fbd735ed-130a-49dd-b68d-c6d5ee09dd97)

_Originally posted by @xiaoxian521 in https://github.com/condorheroblog/vite-plugin-fake-server/issues/4#issuecomment-1780328992_

---

原因：

本插件依赖的 [fast-glob](https://github.com/mrmlnc/fast-glob) 库无法处理 Windows 系统的路径导致的。

为了解决这个问题，需要使用 [convertPathToPattern(path)](https://github.com/mrmlnc/fast-glob#convertpathtopatternpath) 方法进行特殊处理。也就是把 `c:\\Program Files` 转成 `c:/Program Files`。

---

这个插件的开源初衷是为了方便大家使用，我在发布之前已经进行了充分的测试工作。然而，没有百分之百安全的代码，在实际使用过程中，总有一些问题，其中 @xiaoxian521 同学的意见尤其有价值，直戳问题的本质。我要衷心感谢他提出的问题和建议，同时也向他表示歉意，因为我第一时间收到他的消息，但未能及时回复他。为了更好地处理这些反馈，我会花一些时间来仔细思考，在花一些时间采取行动，最后空一些事时间冷却我的方法，确定没问题才会回复。希望 @xiaoxian521 不要介意。

非常感谢，如果还有其他建议或问题，请随时与我交流。

**Comment by xiaoxian521** [comment]
https://github.com/condorheroblog/vite-plugin-fake-server/blob/main/packages/vite-plugin-fake-server/src/node/getFakeFilePath.ts#L33-L36

```
import { platform } from "node:os";

const fakeFolderFiles = fg.sync(
  extensions.map(ext =>
    platform() === "win32"
      ? fg.convertPathToPattern(`${dir}**/*.${ext}`)
      : `${dir}**/*.${ext}`
  ),
  fastGlobOptions
);
```

哈哈 这几天我也在忙 刚回家正好有windows电脑 帮忙处理下 这个库很新很棒💪

**Comment by xiaoxian521** [comment]
在调试过程中发现一些地方 会触发很多次，也就是做很多相同的动作 尤其是刷新页面时，如果页面mock过多（较极端情况下）页面可能会加载也就是白屏一段时间，后续作者有时间优化，可以加个防抖或节流啥的

![image](https://github.com/condorheroblog/vite-plugin-fake-server/assets/44761321/d985ebf1-cc72-4798-b995-4d028951392d)

**Comment by xiaoxian521** [comment]
作者可以把插件加到 https://github.com/vitejs/awesome-vite 大家庭中
就冲它不强绑定mockjs 就很nice

**Comment by condorheroblog** [comment]
> https://github.com/condorheroblog/vite-plugin-fake-server/blob/main/packages/vite-plugin-fake-server/src/node/getFakeFilePath.ts#L33-L36
> 
> ```
> import { platform } from "node:os";
> 
> const fakeFolderFiles = fg.sync(
>   extensions.map(ext =>
>     platform() === "win32"
>       ? fg.convertPathToPattern(`${dir}**/*.${ext}`)
>       : `${dir}**/*.${ext}`
>   ),
>   fastGlobOptions
> );
> ```
> 
> 哈哈 这几天我也在忙 刚回家正好有windows电脑 帮忙处理下 这个库很新很棒💪

对，就是这样，特借了 Windows 电脑测试的😁

**Comment by condorheroblog** [comment]
> 在调试过程中发现一些地方 会触发很多次，也就是做很多相同的动作 尤其是刷新页面时，如果页面mock过多（较极端情况下）页面可能会加载也就是白屏一段时间，后续作者有时间优化，可以加个防抖或节流啥的
> 
> ![image](https://github.com/condorheroblog/vite-plugin-fake-server/assets/44761321/d985ebf1-cc72-4798-b995-4d028951392d)
> 

确实，逻辑需要优化(´･_･`)

**Comment by condorheroblog** [comment]
> 作者可以把插件加到 https://github.com/vitejs/awesome-vite 大家庭中
> 就冲它不强绑定mockjs 就很nice

等稳定了去搞一下，写这个插件主要是 vite-plugin-mock 痛点太多，但是他的想法很好，用的人也很多，我想我能做点啥，就写了写😂

**Comment by xiaoxian521** [comment]
> > https://github.com/condorheroblog/vite-plugin-fake-server/blob/main/packages/vite-plugin-fake-server/src/node/getFakeFilePath.ts#L33-L36
> > ```
> > import { platform } from "node:os";
> > 
> > const fakeFolderFiles = fg.sync(
> >   extensions.map(ext =>
> >     platform() === "win32"
> >       ? fg.convertPathToPattern(`${dir}**/*.${ext}`)
> >       : `${dir}**/*.${ext}`
> >   ),
> >   fastGlobOptions
> > );
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 哈哈 这几天我也在忙 刚回家正好有windows电脑 帮忙处理下 这个库很新很棒💪
> 
> 对，就是这样，特借了 Windows 电脑测试的😁

哈哈 记得我之前写个插件也是 windows路径问题 需要转义 也没win电脑 找同事借的
  platform() === "win32" 这个判断可以放在循环外面 等你下个版本发布 我来帮你测试

**Comment by condorheroblog** [comment]
Windows 电脑坑真是太多了，我借的那个电脑什么环境也没有，重新装环境的时候，老是 npm 包有问题， pnpm 也不行，最后用了 yarn 才可以😌

你那个 pure-admin 写得真不错，下次做 VUE 项目可以用你这个模板🤗

**Comment by xiaoxian521** [comment]
> Windows 电脑坑真是太多了，我借的那个电脑什么环境也没有，重新装环境的时候，老是 npm 包有问题， pnpm 也不行，最后用了 yarn 才可以😌
哈哈 确实 不过win用户最多
> 
> 你那个 pure-admin 写得真不错，下次做 VUE 项目可以用你这个模板🤗
😘

**Comment by condorheroblog** [comment]
[v1.0.2](https://github.com/condorheroblog/vite-plugin-fake-server/releases/tag/v1.0.2) is released
