### ISSUE TITLE
v2 Plan

### ISSUE THREAD

**Issue by condorheroblog** [condorheroblog/vite-plugin-fake-server#6]
A checklist for tracking todos of the next breaking changes

- [x] Support CJS format, Now support `["ts", "js", "mjs", "cjs", "cts", "mts"]`
- [x] Support `infixName` options(`xxx.fake.{ts,js,mjs,cjs,cts,cjs}`) - All fake files with filenames containing fake
- [x] rename `mock` to `fake`- In order to be consistent with fake in the package name(`vite-plugin-fake-server`)
	- [x]  The default value of [include](https://github.com/condorheroblog/vite-plugin-fake-server#include) is changed to fake
	- [x]  [build](https://github.com/condorheroblog/vite-plugin-fake-server#build) The default value of outDir is changed to `fakeServer`
- [x] Bug fixes and optimizations in [watch](https://github.com/condorheroblog/vite-plugin-fake-server#watch) mode
	- [x]  Now it only monitors file updates, but does not monitor file deletions and additions - [plugin.ts#L78](https://github.com/condorheroblog/vite-plugin-fake-server/blob/7e4e8cb53c3741ca7ac7cd681d13a90194b6a39f/packages/vite-plugin-fake-server/src/plugin.ts#L78)
	- [x]  Use HMR strategy when changing files
	- [x]  When loading the fake file for the first time, use the concurrency strategy(5.402s => 1.309s in react-sample)
- [x] revert logger option https://github.com/condorheroblog/vite-plugin-fake-server/issues/7
---

用于跟踪下一个重大变更的待办事项的清单

- [x] 支持 CJS 格式, 现在默认支持的文件是 `["ts", "js", "mjs", "cjs", "cts", "mts"]`
- [x] 支持配置中缀名 `infixName`(`xxx.fake.{ts,js,mjs,cjs,cts,cjs}`) - 所有的 fake 文件，名字要有 fake
- [x] 将 `mock` 重命名为 `fake` - 为了与包名中的 fake 保持一致(`vite-plugin-fake-server`)
	- [x] [include](https://github.com/condorheroblog/vite-plugin-fake-server#include) 默认值改为 fake
	- [x] [build](https://github.com/condorheroblog/vite-plugin-fake-server#build) outDir 默认值改为 `fakeServer`
- [x] [watch](https://github.com/condorheroblog/vite-plugin-fake-server#watch) 模式下的错误修复和优化
	- [x]  现在只监控文件更新，不监控文件删除和添加 - [plugin.ts#L78](https://github.com/condorheroblog/vite-plugin-fake-server/blob/7e4e8cb53c3741ca7ac7cd681d13a90194b6a39f/packages/vite-plugin-fake-server/src/plugin.ts#L78)
	- [x] 更改文件时使用 HMR 策略
	- [x] 第一次加载  fake 文件时，使用并发策略(5.402s => 1.309s 在 react-sample 中等待时间大约减少了 5 倍)
- [x] 恢复 logger 参数 https://github.com/condorheroblog/vite-plugin-fake-server/issues/7

**Comment by xiaoxian521** [comment]
嘿，下面是一些看法

xxx.fake.{ts,js,mjs} - 所有的 fake 文件，名字要有 fake 

每个文件多了个`fake` 其实给用户带来了负担 或者也影响了代码读取的性能 配置暴露尽量随意也符合用户习惯

**Comment by xiaoxian521** [comment]
将 mock 重命名为 fake 其实跟 xxx.fake.{ts,js,mjs} - 所有的 fake 文件，名字要有 fake 是冲突的

所有文件都在 fake 文件夹下 也就意味着这里的文件都属于 fake， 再强制要求用户添加 .fake.  或许有点多余 不要介意哈🤣

**Comment by condorheroblog** [comment]
我是从下面这个角度考虑的：

fake/mock 文件夹下很有可能有这种工具类的函数文件，https://github.com/vbenjs/vue-vben-admin/blob/main/mock/_util.ts 本身并不是 fake/mock 文件，这时候就需要再添加中配置忽略此文件。

如果采用  xxx.fake.{ts,js,mjs} 这种格式，文件本身很有辨识度，工具类等函数可以随意添加，这样无需任何配置，即可开箱即用。

---

另外我新增了 https://github.com/condorheroblog/vite-plugin-fake-server/tree/v2#infixname 来配置中缀名。

**Comment by xiaoxian521** [comment]
好的 请问 infixname 配置 “” 空 是不是就不需要任何中缀了呢 比较大多数情况下 不需要啥工具函数在里面

**Comment by condorheroblog** [comment]
![image](https://github.com/condorheroblog/vite-plugin-fake-server/assets/47056890/4e23d730-1263-4a84-b1e8-41ad38f46633)

对，目前是这样的，听你这么讲，infixName 加上 boolean 类型会比较好😁

**Comment by xiaoxian521** [comment]
哈哈 还真是 
其实`infixname`也相当于 添加中配置忽略此文件

**Comment by condorheroblog** [comment]
我先发布了一个 [v2.0.0-beta.0](https://github.com/condorheroblog/vite-plugin-fake-server/releases/tag/v2.0.0-beta.0) ，所有的 API 应该不会变了，应该也没有 bug，目前测试是这样😂。

里面有部分逻辑，我打算抽出来放到 https://github.com/condorheroblog/bundle-import 然后发布正式版本，如果我不忙的话，明天之前就能完成。

**Comment by xiaoxian521** [comment]
那正好我先用虚拟机搞个windows 来测试测试

**Comment by condorheroblog** [comment]
@xiaoxian521 [v2.0.0](https://github.com/condorheroblog/vite-plugin-fake-server/releases/tag/v2.0.0) is released.

感谢你的帮助，终于完成了，和一个陌生人完成一件还不错的事情，想想就很振奋人心，这是一段愉快的旅程，再次感谢🙏
