### ISSUE TITLE
保留之前的`logger`配置项需求

### ISSUE THREAD

**Issue by xiaoxian521** [condorheroblog/vite-plugin-fake-server#7]
之前的`logger`可以很方便的关闭不想看到的请求信息，而现在只读取`vite`的日志配置有点不方便 比如现在就无法关闭控制台打印的请求日志

**Comment by condorheroblog** [comment]
可以，我放到 v2.0 版本做吧

**Comment by xiaoxian521** [comment]
2.0 大概啥时候呢 😊 我打算集成到 https://github.com/pure-admin/vue-pure-admin 主分支了

**Comment by xiaoxian521** [comment]
`vite-plugin-mock`不完全兼容`vite5` 
`vite-plugin-fake-server`会越来越流行😜

**Comment by condorheroblog** [comment]
> 2.0 大概啥时候呢 😊 我打算集成到 [pure-admin/vue-pure-admin](https://github.com/pure-admin/vue-pure-admin) 主分支了

我在做文件热更新的那部分，主要工作应该都完成了，这个过程，我发现读取文件内容有可能不使用 [bundle-require](https://github.com/egoist/bundle-require)的方法，它采用创建文件，读取完之后删除文件，下面的方法不用异步 IO 读写文件，我在测试这个。

- https://github.com/floatdrop/require-from-string
- https://github.com/exuanbo/module-from-string

**下周五之前肯定发 2.0**。



> `vite-plugin-mock`不完全兼容`vite5` `vite-plugin-fake-server`会越来越流行😜

✌️✌️✌️

**Comment by xiaoxian521** [comment]
哈哈 感谢告知时间 祝`vite-plugin-fake-server`越来越好
