### ISSUE TITLE
[vite-plugin-fake-server] failed to load module from xxx

### ISSUE THREAD

**Issue by xiaoxian521** [condorheroblog/vite-plugin-fake-server#9]
<img width="1290" alt="image" src="https://github.com/condorheroblog/vite-plugin-fake-server/assets/44761321/89910050-5aca-40b6-93dc-56086ba58dfa">

**Comment by xiaoxian521** [comment]
复现代码 https://github.com/pure-admin/vue-pure-admin/tree/refactor/fake-server
复现命令 `pnpm dev`

**Comment by xiaoxian521** [comment]
此处优先导出esm规范 防止升级vite5后可能会带来的cjs即将废弃警告
<img width="860" alt="image" src="https://github.com/condorheroblog/vite-plugin-fake-server/assets/44761321/08d781a0-01ca-4cf9-a866-1722958a9375">

**Comment by xiaoxian521** [comment]
windows这边我可以帮你测试哈 虚拟机已经搞好了😂

**Comment by condorheroblog** [comment]
> 此处优先导出esm规范 防止升级vite5后可能会带来的cjs即将废弃警告 <img alt="image" width="860" src="https://user-images.githubusercontent.com/44761321/281270220-08d781a0-01ca-4cf9-a866-1722958a9375.png">

这个应该没啥问题，因为发布的包默认支持 CJS 和 ESM，项目目录里面有 `"type": "module",` 就会加载 ESM 文件，否则加载 CJS 文件。

**Comment by condorheroblog** [comment]
> <img alt="image" width="1290" src="https://user-images.githubusercontent.com/44761321/281269086-89910050-5aca-40b6-93dc-56086ba58dfa.png">

出现这个问题的原因是插件没有读取 tsconfig paths 里面的定义的别名，不过默认支持 Node.js 定义的别名：https://github.com/condorheroblog/react-antd-admin/commit/5856a2e59e0ded28f56761dbb0ca16eb0dd7153e

不确定需要不需要支持别名，我想应该是一个低频操作。

**Comment by xiaoxian521** [comment]
具体我也不清楚 不过优秀的插件 应该让用户少配置 内部多处理😼

**Comment by xiaoxian521** [comment]
上图的问题会造成请求404

**Comment by condorheroblog** [comment]
> 上图的问题会造成请求404

因为别名的问题，文件没法正常读取，自然数据就没有被插件加载，所以请求会 404，如果需要别名功能，还得需要费点时间开发，应该是在这个 https://github.com/condorheroblog/bundle-import 仓库里面支持。

**Comment by xiaoxian521** [comment]
不急 铁铁 
等你整好@我 我来测试

**Comment by condorheroblog** [comment]
[v2.0.0-beta.1](https://github.com/condorheroblog/vite-plugin-fake-server/releases/tag/v2.0.0-beta.1) is released.

[bundle-import](https://github.com/condorheroblog/bundle-import) 会默认读取 `tsconfig.json` 或者 `jsconfig.json` 里面的 path。

**Comment by xiaoxian521** [comment]
windows 打包后报错

<img width="464" alt="image" src="https://github.com/condorheroblog/vite-plugin-fake-server/assets/44761321/55e58809-9145-4827-aba1-cb9a15b1bda9">

<img width="1174" alt="image" src="https://github.com/condorheroblog/vite-plugin-fake-server/assets/44761321/f5d8fcbd-bf5e-4152-9c42-7ec442cf28a0">

**Comment by xiaoxian521** [comment]
mac打包后没问题 相同的代码 而windows在开发环境下也没有报错

**Comment by xiaoxian521** [comment]
使用 https://github.com/pure-admin/vue-pure-admin/tree/refactor/fake-server 代码
安装依赖后 执行`pnpm preview:build`即可复现

**Comment by xiaoxian521** [comment]
mac打包后预览也会有这个警告 该警告可以消除吗
<img width="524" alt="image" src="https://github.com/condorheroblog/vite-plugin-fake-server/assets/44761321/2d61a0f3-d458-4b47-b34a-ccd75f787b9e">

**Comment by condorheroblog** [comment]
> mac打包后预览也会有这个警告 该警告可以消除吗 <img alt="image" width="524" src="https://user-images.githubusercontent.com/44761321/281650686-2d61a0f3-d458-4b47-b34a-ccd75f787b9e.png">

之前和后端调接口，发现后端地址和 mock 地址重复了，一开始没有想到是重复了，为了避免这个情况，所以线上环境默认不能取消 logger 日志，我想着这样可能好点排查错误。

**Comment by xiaoxian521** [comment]
或许也可以给个配置
```
build.warn: boolean
```

**Comment by condorheroblog** [comment]
> windows 打包后报错
> 
> <img alt="image" width="464" src="https://user-images.githubusercontent.com/44761321/281648082-55e58809-9145-4827-aba1-cb9a15b1bda9.png"> <img alt="image" width="1174" src="https://user-images.githubusercontent.com/44761321/281648265-f5d8fcbd-bf5e-4152-9c42-7ec442cf28a0.png">

我查了下代码，根据以往经验，大致猜出来在哪，我发不了 [v2.0.0-beta.2](https://github.com/condorheroblog/vite-plugin-fake-server/releases/tag/v2.0.0-beta.2) 你再帮我用 Windows build 下🙏

**Comment by xiaoxian521** [comment]
问题还存在哦

**Comment by xiaoxian521** [comment]
或许可以这样 应该是windows的反斜杠路径问题
https://github.com/condorheroblog/vite-plugin-fake-server/commit/6828adfca08c1f19976212ef6d355dfb19076cc7#r132110036

**Comment by condorheroblog** [comment]
Shit 只顾着替换 join 忘了 relative 方法了，发了 beta.3 再试下，不行我就这个 windows 电脑调试完再发版了😅

**Comment by xiaoxian521** [comment]
mac和windows都测试通过
就差那个线上警告啦

**Comment by condorheroblog** [comment]
![image](https://github.com/condorheroblog/vite-plugin-fake-server/assets/47056890/2f9a4a0d-9b6e-4604-ae4b-e8beaa7263ef)


这个线上的 console 目前也不能取消，让他们一起被 logger 控制你看如何，这个解决完，我理解就可以发 2.0 版本了吧😂

**Comment by xiaoxian521** [comment]
如果我设置 logger: false 那打包后线上就没有这个警告了吧？

**Comment by condorheroblog** [comment]
对的，就是这个意思(¬‿¬)👉

**Comment by xiaoxian521** [comment]
👌 还有最后个考虑就是 vite-plugin-fake-server 和实际后端接口同时使用会不会有啥影响 我没具体的测试条件 😂

**Comment by condorheroblog** [comment]
目前逻辑是这样的，无论是生产环境还是开发环境，插件会先校验有没有 mock 这个 URL ，如果没有才会请求服务器，两个不会干扰。

但是如果服务器和 mock 的 URL 重复的话，会优先使用 mock 的 URL，这就是为什么，要在生产环境上把警告和日志强制打开，这样就能判断请求的是真实的 URL 还是 mock 的URL。

**Comment by xiaoxian521** [comment]
好的 坐等正式版🎉
